[package]
name = "euler-rust"
version = "0.1.0"
edition = "2021"
authors = ["Abhishek Banerjee <abhishekbanerjee.iitd+github@gmail.com>"]

[profile.release]
panic = "abort"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"
